/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package travelreview.project;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.image.Image;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;
import travelreview.project.Scenes.LoginScene;
import travelreview.project.Scenes.User_scene.HomeScene;
// import travelreview.project.Scenes.User_scene.ProfileScene;
// import travelreview.project.Scenes.User_scene.TempatListScene;

public class App extends Application {

    @Override
    public void start(Stage stage) {
        stage.setTitle("TravelReview");
        stage.setResizable(false);
        Image appIcon = new Image(getClass().getResourceAsStream("/images/OIG1.jpg"));
        stage.getIcons().add(appIcon);
        
        VBox root = new VBox();
        Scene scene = new Scene(root, 840, 580);
        scene.getStylesheets().add(getClass().getResource("/styles/dark-theme.css").toExternalForm());
        
        stage.setScene(scene);
        stage.show();

        LoginScene loginScene = new LoginScene(stage);
        loginScene.show();
        // HomeScene homeScene = new HomeScene(stage);
        // homeScene.show(1);
        // TempatListScene tempatListScene = new TempatListScene(stage);
        // tempatListScene.show(1);
        // ProfileScene profileScene = new ProfileScene(stage);
        // profileScene.show(2);
    }

    public static void main(String[] args) {
        launch();
    }
}
